### ISSUE TITLE
Add `isFunctionExpression` method

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/eslint-ast-utils#10]
https://github.com/avajs/eslint-plugin-ava/blob/ede93cc4f00a756109cf6bd484f61683d3e639fe/util.js#L40

And use `eslint-ast-utils` there instead.

**Comment by sindresorhus** [comment]
Bonus points for using this in `eslint-plugin-ava`.

**Comment by jfmengels** [comment]
Sure, will do that after I release a new version of this. I would like to implement some more functions you created issues for before doing that :)
